<table>
  <thead>
  <tr>
    <td><?php echo $this->t("Label"); ?></td>
    <td><?php echo $this->t("Address"); ?></td>
    <td><?php echo $this->t("Date Added"); ?></td>
  </tr>
  </thead>
  <tbody>
  <?php foreach($addresses as $address): ?>
    <?php /* @var $address \LoneSatoshi\Models\AddressBook */ ?>
    <tr>
      <td><?php echo $address->name; ?></td>
      <td><?php echo $address->address; ?></td>
      <td><?php echo $address->created; ?></td>
      <td>
        <?php echo $this->l("pay/{$address->address_book_id}/{$address->address}", 'Pay"'); ?>
        <?php echo $this->l("#fixme", "View Transactions"); ?>
      </td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>

<form action="<?php echo $this->url("address-book/add"); ?>" method="post">
  <div class="form-row">
    <label for="name"><?php echo $this->t("Name"); ?>:</label>
    <input id="name" name="name"/>
  </div>
  <div class="form-row">
    <label for="address"><?php echo $this->t("Address"); ?>:</label>
    <input id="address" name="address"/>
  </div>
  <div class="form-row">
    <input type="submit"/>
  </div>
</form>