<table>
  <thead>
    <tr>
      <td class="coin">Coin</td>
      <td colspan="2">Address</td>
      <td colspan="2">Balance</td>
    </tr>
    <tr>
      <td></td>
      <td colspan="2"></td>
      <td>Confirmed</td>
      <td>Unconfirmed</td>
    </tr>
  </thead>
  <tbody>
  <?php foreach($accounts as $account): ?>
    <?php /* @var $account \LoneSatoshi\Models\Account */ ?>
    <tr>
      <td class="coin"><?php echo $account->get_coin()->name; ?></td>
      <td class="address">
        <?php echo $account->address; ?>
      </td>
      <td class="blockchain">
        <?php if($account->get_coin()->chain_url_format_address && $account->get_coin()->chain_name): ?>
          <a href="<?php echo str_replace("::ADDRESS::", $account->address, $account->get_coin()->chain_url_format_address); ?>">
            <?php echo $account->get_coin()->chain_name; ?>
          </a>
        <?php endif; ?>
      </td>
      <td class="confirmed">
        <?php echo ($account->get_balance_confirmed() instanceof \LoneSatoshi\Models\BalanceConfirmed) ? $account->get_balance_confirmed()->balance : 0; ?>
      </td>
      <td class="unconfirmed">
        <?php echo ($account->get_balance_unconfirmed() instanceof \LoneSatoshi\Models\BalanceUnconfirmed) ? $account->get_balance_unconfirmed()->balance : 0; ?>
      </td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>