<table>
  <thead>
  <tr>
    <td>Coin</td>
    <td>Address</td>
    <td>Balance (Confirmed/Unconfirmed)</td>
  </tr>
  </thead>
  <tbody>
  <?php foreach($accounts as $account): ?>
    <?php /* @var $account \LoneSatoshi\Models\Account */ ?>
    <tr>
      <td><?php echo $account->get_coin()->name; ?></td>
      <td><?php echo $account->address; ?></td>
      <td>
        <?php echo ($account->get_balance_confirmed() instanceof \LoneSatoshi\Models\BalanceConfirmed) ? $account->get_balance_confirmed()->balance : 0; ?>
        /
        <?php echo ($account->get_balance_unconfirmed() instanceof \LoneSatoshi\Models\BalanceUnconfirmed) ? $account->get_balance_unconfirmed()->balance : 0; ?>
      </td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>