<?php
$month_ago = strtotime('1 month ago');
$week_ago = strtotime('1 week ago');
$day_ago = strtotime('1 day ago');
$hour_ago = strtotime('1 hour ago');

$cum_btc = 0;
$cum_usd = 0;
$cum_gbp = 0;
?>
<a href="<?php echo $this->url("wallets/add"); ?>" class="btn btn-primary btn-lg" role="button"><?php echo $this->t("Add new Wallet"); ?></a>

<table class="table table-striped wallets">
  <thead>
    <tr>
      <td class="coin"><?php echo $this->t("Coin"); ?></td>
      <td colspan="2"><?php echo $this->t("Address"); ?></td>
      <td colspan="3"><?php echo $this->t("Valuation"); ?></td>
      <td colspan="3"><?php echo $this->t("Balance"); ?></td>
      <td colspan="4"><?php echo $this->t("Rate"); ?></td>
    </tr>
    <tr>
      <td></td>
      <td colspan="2"></td>
      <td><?php echo $this->t("BTC"); ?></td>
      <td><?php echo $this->t("USD"); ?></td>
      <td><?php echo $this->t("GBP"); ?></td>
      <td><?php echo $this->t("Confirmed");?></td>
      <td><?php echo $this->t("Unconfirmed");?></td>
      <td></td>
      <td><?php echo $this->t("Month");?></td>
      <td><?php echo $this->t("Week");?></td>
      <td><?php echo $this->t("Day");?></td>
      <td><?php echo $this->t("Hour");?></td>
    </tr>
  </thead>
  <tbody>
  <?php foreach($accounts as $account): ?>
    <?php
    /* @var $account \LoneSatoshi\Models\Account */
    $transactions_count['month']  = \LoneSatoshi\Models\Transaction::search()->where('account_id',$account->account_id)->where('date', date('Y-m-d H:i:s', $month_ago), ">=")->exec();
    $transactions_count['week']   = \LoneSatoshi\Models\Transaction::search()->where('account_id',$account->account_id)->where('date', date('Y-m-d H:i:s', $week_ago), ">=")->exec();
    $transactions_count['day']    = \LoneSatoshi\Models\Transaction::search()->where('account_id',$account->account_id)->where('date', date('Y-m-d H:i:s', $day_ago), ">=")->exec();
    $transactions_count['hour']   = \LoneSatoshi\Models\Transaction::search()->where('account_id',$account->account_id)->where('date', date('Y-m-d H:i:s', $hour_ago), ">=")->exec();

    foreach($transactions_count as $period => &$values){
      $cumulative = 0;
      foreach($values as $transaction){
        /* @var $transaction \LoneSatoshi\Models\Transaction */
        $cumulative = $cumulative + $transaction->amount;
      }
      $values = $cumulative;
    }

    $o_coin         = $account->get_coin();
    $coin_name      = $o_coin->name;
    $o_confirmed    = $account->get_balance_confirmed();
    $o_unconfirmed  = $account->get_balance_unconfirmed();
    $confirmed      = ($o_confirmed instanceof \LoneSatoshi\Models\BalanceConfirmed) ? $o_confirmed->balance : 0;
    $unconfirmed    = ($o_unconfirmed instanceof \LoneSatoshi\Models\BalanceUnconfirmed) ? $o_unconfirmed->balance : 0;
    $btc            = ($o_confirmed instanceof \LoneSatoshi\Models\BalanceConfirmed) ? $o_confirmed->get_valuation("BTC") : 0;
    $btc_rate       = number_format(\ExchangeApi\Valuations::get_rate($o_coin->symbol, 'BTC'), 8);
    $usd            = ($o_confirmed instanceof \LoneSatoshi\Models\BalanceConfirmed) ? $o_confirmed->get_valuation("USD") : 0;
    $gbp            = ($o_confirmed instanceof \LoneSatoshi\Models\BalanceConfirmed) ? $o_confirmed->get_valuation("GBP") : 0;
    $cum_btc += $btc;
    $cum_usd += $usd;
    $cum_gbp += $gbp;
    ?>

    <tr>
      <td class="coin"><?php echo $coin_name; ?></td>
      <td class="address">
        <?php echo $account->address; ?>
      </td>
      <td class="blockchain">
        <?php if($account->get_coin()->chain_url_format_address && $account->get_coin()->chain_name): ?>
          <a href="<?php echo str_replace("::ADDRESS::", $account->address, $account->get_coin()->chain_url_format_address); ?>">
            <?php echo $account->get_coin()->chain_name; ?>
          </a>
        <?php endif; ?>
      </td>
      <td class="valuation-btc" title="<?php echo "{$confirmed} at {$btc_rate}"; ?>"><?php echo number_format($btc, 8); ?></td>
      <td class="valuation-usd"><?php echo number_format($usd, 2); ?></td>
      <td class="valuation-gbp"><?php echo number_format($gbp, 2); ?></td>
      <td class="confirmed"><?php echo number_format($confirmed, 8); ?></td>
      <td class="unconfirmed"><?php echo number_format($unconfirmed, 8); ?></td>
      <td><a href="<?php echo $this->url("transactions/refresh/{$account->account_id}");?>" class="btn btn-warning btn-xs"><?php echo $this->t("Refresh"); ?></a></td>
      <td class="rate rate-month"><?php echo number_format($transactions_count['month'],0); ?></td>
      <td class="rate rate-week"><?php echo number_format($transactions_count['week'],0); ?></td>
      <td class="rate rate-day"><?php echo number_format($transactions_count['day'],0); ?></td>
      <td class="rate rate-hour"><?php echo number_format($transactions_count['hour'],0); ?></td>
    </tr>
  <?php endforeach; ?>
  </tbody>
  <tfoot>
  <tr>
    <td class="coin">Total</td>
    <td class="address"></td>
    <td class="blockchain"></td>
    <td class="valuation-btc"><?php echo number_format($cum_btc, 8); ?></td>
    <td class="valuation-usd"><?php echo number_format($cum_usd, 2); ?></td>
    <td class="valuation-gbp"><?php echo number_format($cum_gbp, 2); ?></td>
    <td class="confirmed"></td>
    <td class="unconfirmed"></td>
    <td></td>
    <td class="rate rate-month"></td>
    <td class="rate rate-week"></td>
    <td class="rate rate-day"></td>
    <td class="rate rate-hour"></td>
  </tr>
  </tfoot>
</table>