<table class="table table-striped transactions">
  <thead>
  <tr>
    <td>Transaction ID</td>
    <td>Coin</td>
    <td>Address</td>
    <td>Amount</td>
    <td>Confirmations</td>
    <td>Refresh</td>
    <td>TX ID</td>
    <td>Date</td>
    <td>Block Hash</td>
    <td>Block Index</td>
  </tr>
  </thead>
  <tbody>
  <?php foreach($transactions as $transaction): ?>
    <?php /* @var $transaction \LoneSatoshi\Models\Transaction */ ?>
    <tr class="<?php echo $transaction->category?>">
      <td class="transaction_id"><?php echo $transaction->transaction_id; ?></td>
      <td class="coin"><?php echo $transaction->get_account()->get_coin()->name; ?></td>
      <td class="address">
        <?php if($transaction->get_account()->get_coin()->chain_url_format_address): ?>
          <a href="<?php echo str_replace("::ADDRESS::", $transaction->address, $transaction->get_account()->get_coin()->chain_url_format_address); ?>" title="<?php echo $transaction->address; ?>">
            <?php echo substr($transaction->address, 0, 7); ?>
          </a>
        <?php else: ?>
          <span title="<?php echo $transaction->address; ?>"><?php echo substr($transaction->address, 0, 7); ?></span>
        <?php endif; ?>
      </td>
      <td class="amount"><?php echo number_format($transaction->amount,10); ?></td>
      <td class="confirmations"><?php echo $transaction->confirmations; ?></td>
      <td class="refresh"><a href="<?php echo $this->url("transactions/refresh/{$transaction->get_account()->account_id}");?>" class="btn btn-warning btn-xs"><?php echo $this->t("Refresh"); ?></a></td>
      <td class="txid">
        <?php if($transaction->get_account()->get_coin()->chain_url_format_transaction): ?>
          <a href="<?php echo str_replace("::TXID::", $transaction->txid, $transaction->get_account()->get_coin()->chain_url_format_transaction); ?>" title="<?php echo $transaction->txid; ?>">
            <?php echo substr($transaction->txid, 0, 7); ?>
          </a>
        <?php else: ?>
          <span title="<?php echo $transaction->txid; ?>"><?php echo substr($transaction->txid, 0, 7); ?></span>
        <?php endif; ?>
      </td>
      <td class="date"><?php echo $transaction->date; ?></td>
      <td class="blockhash"><span title="<?php echo $transaction->block_hash; ?>"><?php echo substr($transaction->block_hash, 0, 7); ?></span></td>
      <td class="blockindex"><?php echo $transaction->block_index; ?></td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>