<div class="container-fluid-full">
  <div class="row-fluid">

    <div class="row-fluid">
      <div class="login-box">
        <div class="icons">
          <a href="/"><i class="halflings-icon home"></i></a>
        </div>
        <h2><?php echo $this->t("Login to your " . APP_NAME . " account"); ?></h2>
        <form method="post" action="" class="form-horizontal">
          <fieldset>

            <div title="Username" class="input-prepend">
              <span class="add-on"><i class="halflings-icon user"></i></span>
              <input type="text" placeholder="type username" id="username" name="username" class="input-large span10">
            </div>
            <div class="clearfix"></div>

            <div title="Password" class="input-prepend">
              <span class="add-on"><i class="halflings-icon lock"></i></span>
              <input type="password" placeholder="type password" id="password" name="password" class="input-large span10">
            </div>
            <div class="clearfix"></div>

            <div class="button-login">
              <button class="btn btn-primary" type="submit"><?php echo $this->t("Login"); ?></button>
            </div>
            <div class="clearfix"></div>

            <hr>
            <h3><?php echo $this->t("Forgot Password?"); ?></h3>
            <p><?php echo $this->t("No problem, you can ") . $this->link('user/password-reset',$this->t("reset your password")); ?></p>
            <h3><?php echo $this->t("Not a :sitename user yet?", array(':sitename'=>$this->getSiteTitle(false))); ?></h3>
            <p><?php echo $this->t("You can ") . $this->link('register',$this->t("sign up")) . $this->t(" for free!"); ?></p>
          </fieldset>
        </form>
      </div><!--/span-->
    </div><!--/row-->


  </div><!--/.fluid-container-->

</div>