<form action="<?php echo $this->url("pay/{$address_book_record_id}/{$address}"); ?>" method="post">
  <input type="hidden" name="pre-transaction-id" value="<?php echo $pre_transaction_id; ?>"/>
  <div class="form-row">
    <label for="amount"><?php echo $this->t("Pay Amount to :address:", array(':address' => $address)); ?>:</label>
    <input id="amount" name="amount"/>
  </div>
  <div class="form-row">
    <input class="btn btn-danger" type="submit"/>
  </div>
</form>

<p><?php echo $this->t("You have :amount :coin available", array(':amount' => $available_balance, ':coin' => $coin->symbol)); ?></p>