<script type="text/javascript">
  var valuations = <?php echo json_encode($valuations); ?>;
  google.load("visualization", "1", {packages:["corechart"]});
  google.setOnLoadCallback(drawChart);
  function drawChart() {
    for ( var i = 0; i < valuations.rows.length; i++ ) {
      valuations.rows[i].c[0].v = new Date( valuations.rows[i].c[0].v * 1000 );
    }
    console.log(valuations);

    var data = google.visualization.arrayToDataTable(valuations);

    var options = {
      title: 'Company Performance'
    };

    var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
    chart.draw(data, options);
  }
</script>

<div id="chart_div"></div>


